# Generated by Django 4.2.13 on 2024-07-18 15:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feured_image', models.ImageField(upload_to='Images')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], max_length=100)),
                ('section', models.CharField(choices=[('news', 'news'), ('product', 'product'), ('event', 'event')], max_length=200)),
            ],
        ),
    ]
