# Generated by Django 4.2.13 on 2024-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aboutus_events_gallery_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
