# Generated by Django 4.2.13 on 2024-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contectinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('linkdin', models.CharField(max_length=200)),
            ],
        ),
    ]
