# Generated by Django 4.2.13 on 2024-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contectinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feured_image', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
