# Generated by Django 4.2.13 on 2024-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_logof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='doc/')),
                ('imageq', models.ImageField(upload_to='Images')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='imageq',
            field=models.ImageField(default=1, upload_to='Images'),
            preserve_default=False,
        ),
    ]
